package com.softdesign.devintensive.utils;

public interface ConstantManager {
    String TAG_PREFIX = "DEV ";
    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_MAIL_KEY = "USER_MAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GITHUB_KEY = "USER_GITHUB_KEY";
    String USER_BIO_KEY = "USER_BIO_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String USER_AVATAR_KEY = "USER_AVATAR_KEY";
    String AUTH_TOKEN_KEY= "AUTH_TOKEN_KEY";
    String USER_ID_KEY= "USER_ID_KEY";
    String USER_RATING_VALUE = "USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECTS_VALUE = "USER_PROJECTS_VALUE";
    String CONTENT_PHONE_VALUES = "CONTENT_PHONE_VALUES";
    String CONTENT_EMAIL_VALUES = "CONTENT_EMAIL_VALUES";
    String CONTENT_GIT_VALUES = "CONTENT_GIT_VALUES";
    String CONTENT_VK_VALUES = "CONTENT_VK_VALUES";
    String CONTENT_BIO_VALUES = "CONTENT_BIO_VALUES";
    String NAV_FIRST_NAME_VALUES = "NAV_FIRST_NAME_VALUES";
    String NAV_SECOND_NAME_VALUES = "NAV_SECOND_NAME_VALUES";
    String NAV_AVATAR_VALUES = "NAV_AVATAR_VALUES";

    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE = 99;
    int REQUEST_GALLERY_PICTURE = 88;

    int PERMISSION_REQUEST_SETTINGS_CODE = 101;
    int CAMERA_REQUEST_PERMISSION_CODE = 102;

    int CALL_PHONE_REQUEST_PERMISSIONS_CODE = 103;
}